### ISSUE TITLE
shit is owo.sh

### ISSUE THREAD

**Issue by memanlolz** [whats-this/owo.sh#10]
fix pls
<extension of #9 >

**Comment by OkashiOdayakana** [comment]
you gotta ask the devs of `shit` for that. Closing issue

**Comment by memanlolz** [comment]
oh sorry my bad, will tell them. thank you. Meanwhile, can you tell me why `owo.sh === shit`?

**Comment by aurieh** [comment]
🔪 🔪 🔪 Shame for spamming my github notifs 🔪 🔪 🔪

**Comment by zet4** [comment]
🔔 Shame 🔔 Shame 🔔 Shame 🔔 Shame 🔔 Shame 🔔 Shame 🔔

**Comment by itslukej** [comment]
owo.sh more like owo.shit

**Comment by jakeoid** [comment]
Removed all comments, can we not please?
