### ISSUE TITLE
can not upload file with spaces in name

### ISSUE THREAD

**Issue by mralext20** [whats-this/owo.sh#27]
```sh
[alexander@alexlaptop ~]$ owo -ul Pictures/Screenshot\ from\ 2017-07-30\ 19-00-16.png 
Pictures/Screenshot not found! Exiting...
```

i think this can be fixed by listening to escape characters.

system: arch linux, using the AUR package version 0.0.19

**Comment by Mstrodl** [comment]
@mralext20 Did you try putting quotes around the name? 🤔

**Comment by mralext20** [comment]
Yeap: 
https://memework.is-serious.business/8f075f.png

**Comment by ArsenArsen** [comment]
The escape characters are interpreted by the shell.

This can be fixed by having all strings surrounded by `"` and would be the most practical solution to implement and use.

**Comment by OkashiOdayakana** [comment]
Yeah, I'll try to look into this

_Sent from my Google Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by OkashiOdayakana** [comment]
Will look into
