### ISSUE TITLE
Fourchin.net cant be resolved

### ISSUE THREAD

**Issue by itskiru** [whats-this/owo.sh#29]
Hi,

I tried to use `curl https://fourchin.net/owo.sh | bash` but got that error message: `curl: (6) Could not resolve host: fourchin.net`. Can you fix the domain pls ?

**Comment by aurieh** [comment]
@itskiru you could use `curl -L https://owo.sh | bash`, at least for now
@OkashiOdayakana README.md could use this domain

**Comment by itskiru** [comment]
@aurieh well u should change into the repo too 
![image](https://user-images.githubusercontent.com/25879000/30005735-4a58372c-90e9-11e7-9c19-5d36711328c0.png)
