### ISSUE TITLE
slop: invalid option -- 'q' when using 'owo -gr'

### ISSUE THREAD

**Issue by deatcoca** [whats-this/owo.sh#37]
I really don't understand where this problem comes from, i have `slop v4.2.20`, and my distro is KDE Neon and when I use the command `owo -gr` it gives me the following error:
- slop: invalid option -- 'q' 
Despite the fact that slop's documentation talks about this arguments: 
- o.bool '-q', '--quiet', 'suppress output (quiet mode)'

I tried to replace `-q` by `--quiet` in script.sh, just like in this PR about maim ( #35 ) but it outputs:
- slop: unrecognized option '--quiet'

So tell me if you have any ideas why slop is acting like that on my distro :thinking:

**Comment by aurieh** [comment]
That's an outdated version of slop, stable is at version 6 and master branch is version 7.
Please try building from source.

**Comment by deatcoca** [comment]
I see, I thought it was weird because my version is the latest on the ubuntu repo.
I'll build it from source. Thank you for your answer!

**Comment by deatcoca** [comment]
Okay so i just found out that there's two applications named slop, one written [in Ruby](https://github.com/leejarvis/slop) and one written [in C++](https://github.com/naelstrof/slop). 
And I discovered that i had installed the Ruby one, which of course is not the good one.
