### ISSUE TITLE
[deps/required] dnf cannot find maim or slop, alternatives?

### ISSUE THREAD

**Issue by ZaneHannanAU** [whats-this/owo.sh#39]
```terminal-session
[zeen3@zeen3 ~]$ bash owo.sh 
Cloning git repository...
Running setup.sh...
FOUND : found notify-send
Maim not found. Please install it via your package manager.
FOUND : found xclip
Slop not found. Please install via your package manager.

Please install the missing dependencie(s) then run this script again.
[zeen3@zeen3 ~]$ sudo  dnf install maim Maim slop Slop -y
[sudo] password for zeen3: 
Last metadata expiration check: 1:21:18 ago on Tue 02 Jan 2018 12:14:51 AEDT.
No match for argument: maim
No match for argument: Maim
No match for argument: slop
No match for argument: Slop
Error: Unable to find a match
[zeen3@zeen3 ~]$ 
```

Looking for the required packages, findable?

**Comment by itskiru** [comment]
Which OS?

**Comment by ZaneHannanAU** [comment]
@itskiru
Linux/Red Hat Fedora 26, using dnf 2.7.5.

**Comment by MeltedLux** [comment]
Real distro recommended.

**Comment by MeltedLux** [comment]
But for real, you'll need to compile them.

https://github.com/naelstrof/maim
https://github.com/naelstrof/slop

**Comment by ArsenArsen** [comment]
Check copr, and upgrade

**Comment by itskiru** [comment]
You need to use CMAKE: 

https://github.com/naelstrof/slop#install-using-cmake-requires-cmake

https://github.com/naelstrof/maim#install-using-cmake-requires-cmake-git-libxrander-libxfixes-libglm

If you don't have the good dependencies, look on their github page for compilation method.

**Comment by ZaneHannanAU** [comment]
Thank you, will do 😃
