### ISSUE TITLE
I locked myself out of my main Discord account send help

### ISSUE THREAD

**Issue by OkashiOdayakana** [whats-this/owo.sh#40]
Oops forgot how to backup my 2fa shit before I unlock my bootloader and get my phone wiped someone send owo invite pls

**Comment by OkashiOdayakana** [comment]
My (possibly) new account ID is 370045725574168576

**Comment by deansheather** [comment]
This is not the place to discuss this. You can email the email address on the website for help.

**Comment by OkashiOdayakana** [comment]
Wew smh

**Comment by OkashiOdayakana** [comment]
Can't even yell on my own project smh

**Comment by deansheather** [comment]
Oh yeah, I forgot you were a contributor lmao. Send me a DM on Discord, Dean#9114.

Or send me that email I guess.
