### ISSUE TITLE
owo.sh is shit

### ISSUE THREAD

**Issue by OkashiOdayakana** [whats-this/owo.sh#9]
pls fix

**Comment by zet4** [comment]
No.

**Comment by aurieh** [comment]
trashing my github feed again >->

**Comment by OkashiOdayakana** [comment]
tru

**Comment by OkashiOdayakana** [comment]
Ill lock I guess

**Comment by zet4** [comment]
Nice lock
![image](https://cloud.githubusercontent.com/assets/1717852/22039614/a878aeb2-dd08-11e6-80ef-d22f6195804d.png)

**Comment by aurieh** [comment]
@zet4 🔪
